title: Nicholas Gonsalves
description: 

baseurl: ""
url: "https://npg002.github.io/"

footer_links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: npg002
  instagram: 
  linkedin: nicholas-gonsalves-0a70a452
  pinterest: 
  rss: 
  twitter: 
  stackoverflow: 
  youtube: 
  googleplus: 

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
